apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  annotations:
    description: "Initial deployment"
    contact: "admin@example.com"
spec:
  imagePullSecrets:
  - name: regcred
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
      annotations:
        example.com/revision: "1"
        example.com/configHash: "abcd1234"
    spec:
      containers:
      - name: myapp
        image: nginx:1.19.3

