apiVersion: v1
kind: Service
metadata:
  name: annotated-service
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "myapp.example.com"
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376

