apiVersion: apps/v1
kind: Deployment
metadata:
  name: annotated-deployment
  annotations:
    deployment.kubernetes.io/revision: "1"
    example.com/config-hash: "abcd1234"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: myapp
        image: nginx:latest

