# rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo-rolebinding
  namespace: demo-app
subjects:
- kind: ServiceAccount
  name: demo-sa
  namespace: demo-app
roleRef:
  kind: Role
  name: demo-role
  apiGroup: rbac.authorization.k8s.io
