# demo-user-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo-user-binding
  namespace: rbac-demo
subjects:
- kind: ServiceAccount
  name: demo-user
  namespace: rbac-demo
roleRef:
  kind: Role
  name: escalate-and-bind-role
  apiGroup: rbac.authorization.k8s.io

