# high-privilege-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: rbac-demo
  name: high-privilege-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete", "update", "get", "list"]

