# another-user-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: another-user-binding-1
  namespace: rbac-demo
subjects:
- kind: ServiceAccount
  name: another-user-1
  namespace: rbac-demo
roleRef:
  kind: Role
  name: high-privilege-role
  apiGroup: rbac.authorization.k8s.io
